### PR TITLE
Issue 7: Landing page: Slider

### PR DESCRIPTION
**Pull request by tmathern**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix Issue 7 (partial).

Test URLs:
- Before: https://main--caesars-careers--hlxsites.hlx.page/drafts/mathern/slider
- After: https://issue-7-slider-v2--caesars-careers--hlxsites.hlx.page/drafts/mathern/slider

Follow-up of https://github.com/hlxsites/caesars-careers/pull/23.
Moves over sliders from https://github.com/hlxsites/caesars.

### CODE REVIEW

**Comment by tmathern** [comment]
https://github.com/hlxsites/caesars-careers/issues/7

**Comment by swetabar** [comment]
Screen Shot 2023-05-04 at 7 12 40 AM

The chevron arrows seem to be missing.

**Comment by arumsey** [comment]
This PR seems to include portions of https://github.com/hlxsites/caesars-careers/pull/23 as well.

**Comment by tmathern** [comment]
To be reworked with @swetabar

**Pull request closed without merging**
