### PR TITLE
Issue 44: Tabs

### PR DESCRIPTION
**Pull request by tmathern**
Fix https://github.com/hlxsites/caesars-careers/issues/44

## 🔗 Test URLs:

- Before: https://main--caesars-careers--hlxsites.hlx.page/drafts/mathern/tabs
- After: https://issue-44--caesars-careers--hlxsites.hlx.page/drafts/mathern/tabs

## 📝 Description:
- Adds tabs (for https://www.caesars.com/careers/apply)
- Styling color changes to be done in https://github.com/hlxsites/caesars-careers/issues/22

### CODE REVIEW

**Comment by amol-anand** [comment]
Icons to move left/right in mobile seem to be missing

**Comment by tmathern** [comment]
FIxed icon naming - so the icons should be back in and visible on mobile!

**Review by amol-anand — APPROVED** [review]
Merge for now and add an issue to relook at whether we can move the mobile vs desktop stuff to CSS rather than JS.

**Comment by tmathern** [comment]
https://github.com/hlxsites/caesars-careers/issues/52

**Pull request merged**
